# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mysite.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('alt', models.CharField(blank=True, max_length=128, null=True)),
                ('image', models.ImageField(help_text='900px * 420px', upload_to=mysite.models.upload_file)),
                ('width', models.DecimalField(decimal_places=1, default=300, max_digits=5)),
                ('height', models.DecimalField(decimal_places=1, default=200, max_digits=5)),
                ('status', models.CharField(choices=[('a', 'active'), ('b', 'Inactive')], default='a', max_length=1)),
                ('href', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': '3. Banner',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('zip_code', models.IntegerField()),
                ('state', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('phone', models.IntegerField()),
                ('currency', models.CharField(default='€', max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Πληροφορίες Καταστήματος',
            },
        ),
        migrations.CreateModel(
            name='EshopAskQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number', models.IntegerField(default=1)),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'FAQ',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='EshopInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Όνομα Εταιρίας')),
                ('address', models.TextField(blank=True, help_text='For the contact page', null=True)),
                ('call_center', models.TextField(blank=True, help_text='For the contact page', null=True)),
                ('support', models.TextField(blank=True, help_text='For the contact page', null=True)),
                ('info_text', models.TextField(help_text='url: info_eshop', null=True)),
            ],
            options={
                'verbose_name_plural': 'Πληροφορίες για την Contact Page',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(default='default', max_length=100, unique=True)),
                ('category_name_1', models.CharField(max_length=100)),
                ('category_name_2', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '6. Footer',
            },
        ),
        migrations.CreateModel(
            name='FooterCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Footer')),
            ],
        ),
        migrations.CreateModel(
            name='FrontPageMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('style_of', models.CharField(help_text='announcement,information,success,warning,error', max_length=100)),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': '4. Μήνυμα Αρχικής Σελίδας',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Το Μοναστηράκι', max_length=50)),
                ('alt', models.CharField(default='Το Μοναστηράκι', max_length=50)),
                ('image', models.ImageField(upload_to=mysite.models.upload_file)),
            ],
        ),
        migrations.CreateModel(
            name='OfferPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Ενεργό')),
                ('title', models.CharField(max_length=50, verbose_name='Tίτλος')),
                ('text', models.CharField(max_length=200, verbose_name='Link')),
                ('href', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name_plural': '2. Ανακοίνωση Προσφοράς',
            },
        ),
        migrations.CreateModel(
            name='SecondSectionBanners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=128)),
                ('alt', models.CharField(max_length=128)),
                ('image', models.ImageField(help_text='908px * 410px', upload_to=mysite.models.upload_file)),
                ('href', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': '5. Δεύτερα Banners',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default', max_length=50, unique=True)),
                ('last_products_qty', models.IntegerField(default=20)),
                ('default_months_for_report', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('priority', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='WelcomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=128, verbose_name='Ονομασία Site')),
                ('logo', models.ImageField(blank=True, help_text='139*60', upload_to=mysite.models.upload_file)),
                ('logo_small', models.ImageField(blank=True, help_text='93*60', upload_to=mysite.models.upload_file)),
                ('phone_number', models.CharField(max_length=10)),
                ('phone_title_pop', models.CharField(blank=True, help_text='Its the title of the popup on phone nav bar', max_length=100)),
                ('phone_content_pop', models.TextField(help_text='The content', max_length=100)),
                ('info', models.CharField(blank=True, max_length=100)),
                ('info_title_pop', models.CharField(blank=True, help_text='navbar info title', max_length=100)),
                ('info_content_pop', models.TextField(help_text='navbar info content', max_length=100)),
                ('login_text', models.CharField(blank=True, max_length=100)),
                ('sign_in_text', models.CharField(blank=True, max_length=100)),
                ('signed_in_text', models.CharField(blank=True, max_length=100)),
                ('order_text', models.CharField(blank=True, max_length=100)),
                ('seo_keywords', models.CharField(blank=True, max_length=160, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=160, null=True)),
            ],
            options={
                'verbose_name_plural': '1.Διαχείριση Αρχικής Σελίδας',
            },
        ),
        migrations.AddField(
            model_name='userterms',
            name='related_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.WelcomePage'),
        ),
        migrations.AddField(
            model_name='secondsectionbanners',
            name='page_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.WelcomePage'),
        ),
        migrations.AddField(
            model_name='offerpage',
            name='page_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.WelcomePage'),
        ),
        migrations.AddField(
            model_name='frontpagemessages',
            name='page_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.WelcomePage'),
        ),
    ]
