# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Όνομα')),
                ('last_name', models.CharField(max_length=50, verbose_name='Επίθετο')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50, verbose_name='Θέμα')),
                ('message', models.TextField(verbose_name='Μήνυμα')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Αποστολής')),
                ('is_readed', models.BooleanField(default=False, verbose_name='Διαβασμένο')),
            ],
            options={
                'verbose_name_plural': 'Μηνύματα Επικοινωνίας',
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='NewsLetterEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.NewsLetterEmail', unique=True)),
            ],
        ),
    ]
