# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 05:51
from __future__ import unicode_literals

import PoS.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestroyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=PoS.models.create_destroy_title, max_length=15)),
                ('day_added', models.DateTimeField(auto_now=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('notes', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DestroyOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('qty', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('day_added', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('sort_id', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['sort_id'],
            },
        ),
        migrations.CreateModel(
            name='RetailOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('order_type', models.CharField(choices=[('r', 'retail'), ('e', 'eshop'), ('b', 'return'), ('d', 'destroy')], max_length=1)),
                ('day_created', models.DateTimeField(default=datetime.datetime(2017, 6, 28, 8, 51, 55, 337329))),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Έκπτωση')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Αξία Παραγγελίας')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Συνολικό Κόστος Παραγγελίας')),
                ('paid_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Αποπληρωμένο Πόσο')),
                ('taxes', models.IntegerField(default=24)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('day_sent', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('cellphone', models.IntegerField(blank=True, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('costumer_submit', models.BooleanField(default=True)),
                ('eshop_order_id', models.CharField(blank=True, max_length=10, null=True)),
                ('eshop_session_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RetailOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Τιμή Μονάδας')),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Ποσότητα')),
                ('day_added', models.DateField(auto_now=True)),
                ('is_find', models.BooleanField(default=False)),
                ('is_return', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PoS.RetailOrder')),
            ],
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('content', models.CharField(default='Input here', max_length=300)),
                ('active', models.CharField(choices=[('a', 'Active'), ('b', 'Inactive')], max_length=1)),
                ('for_site', models.BooleanField(default=True, verbose_name='Ενεργό για το Site')),
            ],
        ),
    ]
