# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToolsTableOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('show_number_of_products', models.IntegerField(default=50, verbose_name='Επέλεξε Πόσα Προιόντα θα εμφανίζονται ')),
                ('width', models.IntegerField(default=120, verbose_name='Μήκος Τραπεζιού')),
                ('height', models.IntegerField(default=600, verbose_name='Υψος Τραπεζιού')),
                ('table_order_by', models.CharField(blank=True, default=None, max_length=100, verbose_name='')),
            ],
        ),
    ]
