# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-02 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=60, unique=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('type_of_discount', models.CharField(choices=[('a', 'Ποσοστό'), ('b', 'Ποσό')], max_length=1)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
                ('query_set', models.ManyToManyField(to='products.Product')),
            ],
        ),
    ]
