# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-02 13:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0002_auto_20170628_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 7, 2, 16, 6, 33, 124165)),
        ),
    ]
