# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-10 19:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0004_auto_20170705_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 7, 10, 22, 24, 29, 42927)),
        ),
    ]
